# Generated by Django 5.1.7 on 2025-03-11 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_otphandler_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otphandler',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
