# Generated by Django 5.2 on 2025-04-08 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_deleted_by_message_hidden_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
