# Generated by Django 5.1.7 on 2025-03-12 08:25

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='productSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'productSubcategory',
            },
        ),
        migrations.CreateModel(
            name='produtcCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'produtCategory',
            },
        ),
        migrations.CreateModel(
            name='productStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Unsold', 'Unsold'), ('Deleted', 'Deleted')], default='Unsold', max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtccategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='product_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='products.productstore')),
            ],
            options={
                'db_table': 'products_photos',
            },
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtccategory'),
        ),
    ]
