# Generated by Django 5.1.7 on 2025-03-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='products.produtccategory'),
        ),
    ]
