# Generated by Django 5.1.7 on 2025-03-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsubcategory_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='carModel',
            fields=[
                ('productstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productstore')),
                ('type', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('km_driven', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
            bases=('products.productstore',),
        ),
    ]
