# Generated by Django 5.1.7 on 2025-03-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikeModel',
            fields=[
                ('productstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productstore')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('model_year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
            ],
            options={
                'db_table': 'Bikes',
            },
            bases=('products.productstore',),
        ),
    ]
