# Generated by Django 5.1.7 on 2025-03-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_photos_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_photos',
            name='photos',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
