# Generated by Django 5.1.7 on 2025-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_photos_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='display_photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
