# Generated by Django 5.1.7 on 2025-03-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_mobilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
