# Generated by Django 5.1.7 on 2025-03-18 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productstore_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtccategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstore')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubcategory')),
            ],
            options={
                'db_table': 'produc_details',
            },
        ),
    ]
