# Generated by Django 5.1.7 on 2025-03-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productdetails_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='display_photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
