# Generated by Django 5.1.7 on 2025-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productstore_display_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_photos',
            name='photos',
            field=models.ImageField(upload_to=''),
        ),
    ]
